In [3]:
import numpy as np
import random as r

In [5]:
# numpy는 다차원 배열을 쉽고, 효율적으로 사용할 수 있게 돕는 라이브러리
# 대표적인 데이터분석 라이브러리

In [7]:
# ndarray
# 파이썬의 list기능을 보완하고, 행렬을 다루는 자료형

# 다차원 행렬? 2차원을 예로들자
# 1행이 2개의 열을 보유하면
# 2행도 2개의 열을 보유해야 성립

# 리스트의 더하기연산은 그냥 리스트의 연결이다.
# ndarray는 행렬의 연산, 같은 위치에 있는 열끼리 덧셈 연산 실행.
# 그래서 길이가 다른 ndarray끼리의 연산은 수행하지 않음


In [ ]:
# 차원과 축!

#1D [1,2,3] 1차원 데이터. 모든 요소가 스칼라
#2D [[1,2],[3,4]] 2차원의 데이터. 
#3D [ [[1],[2]],[[3],[4]] ] 3차원의 데이터.

#axis=0 행 방향(세로축)
#0
#0
#0
#axis=1 열 방향(가로축)
#0000000

### ndarray
- NumPy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [ ]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
d=np.array([1.0, 2.0, 7.6])

print(f"배열의 구조: {a.shape}") # 2행 3열
print(f"배열의 차원: {a.ndim}") # 2차원 배열
print(f"a배열의 데이터타입: {a.dtype}") # 정수형 64비트(=8바이트)

print(f"b배열의 데이터타입: {d.dtype}")

new_a=a.astype(np.float64)
print(f"수정한 a 배열의 데이터타입: {new_a.dtype}")

배열의 구조: (2, 3)
배열의 차원: 2
배열의 데이터타입: int64
b배열의 데이터타입: float64


In [ ]:
# 3차원 행렬
a=np.array([[[1,2,3],[4,5,6]],
            [[1,2,3],[4,5,6]],
            [[1,2,3],[4,5,6]],
            [[1,2,3],[4,5,6]],
            ])


print(f"배열의 구조: {a.shape}") # 4개 있다, 2행이고 3열인 2차원 행렬이
print(f"배열의 차원: {a.ndim}") # 3차원 배열

배열의 구조: (4, 2, 3)
배열의 차원: 3


In [ ]:
# 4차원 배열 정의
a = np.array([
    [  # # 첫 번째 3차원 블록 (4개의 2x3 행렬)
        [[1, 2, 3], [4, 5, 6]],   # 2행 3열 2차원 배열로 이루어진 3차원 배열
        [[1, 2, 3], [4, 5, 6]],
        [[1, 2, 3], [4, 5, 6]],
        [[1, 2, 3], [4, 5, 6]],
    ],
    [  
        [[1, 2, 3], [4, 5, 6]],
        [[1, 2, 3], [4, 5, 6]],
        [[1, 2, 3], [4, 5, 6]],
        [[1, 2, 3], [4, 5, 6]],
    ]
])

print(f"배열의 구조: {a.shape}")   # (2개 있다, 4행의 3차원 배열이, 2행의 2차원 배열을 가졌다. 3개의 열을 가진 2차원 배열을.) = (2,4,2,3)
print(f"배열의 차원: {a.ndim}")   # 4차원 배열



배열의 구조: (2, 4, 2, 3)
배열의 차원: 4


In [ ]:
# 기본자료형은 float 이기 때문에 명시적으로 int 저장해주면 int 가 된다

np.zeros((3,4),dtype=np.int64) # 2차원
np.zeros((2,3,4),dtype=np.int64) # 3차원

# 2행 3열
np.ones((2,3),dtype=np.int64)


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# 구조는 정의됐지만 원소의 값이 초기화 되지 않은 배열 생성
np.empty((5,3))
# 메모리에 존재하는 가비지값이 찍히는것이다.

array([[ 0.    ,  0.    ,  1.    ],
       [ 0.0625,  0.25  ,  1.    ],
       [ 1.    ,  1.    ,  1.    ],
       [ 5.0625,  2.25  ,  1.    ],
       [16.    ,  4.    ,  1.    ]])

In [ ]:
np.full((3,3),7)
# 지정한 값으로 배열을 채운다

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
# 단위행렬? 대각선(좌상에서 우측아래까지 그것만 1)
# 행렬의 곱 연산
# 행렬의 곱 계산, 단위행렬을 곱하면 원래 자기자신의 값이 나온다.

In [ ]:
np.eye(3,3)

# 세번째 인자 넣기
np.eye(3,5,1)
# 옆으로 한 칸 대각선이 이동. 1은 k값 

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [33]:
np.arange(0,10,2) # 2의 간격으로 10까지 레인지의 간격 
# ( 시작이상, 끝미만, 간격)

np.arange(0,10) # 간격지정 안하면 1부터

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# linespace = 시작-끝까지 균일간격으로 숫자를 생성합니다
# 지정한 범위 내 지정한 갯수만큼 균일한 간격으로 숫자를 생성

np.linspace(10,100,10)
np.linspace(0.1,1,10)

# reshape: 배열 구조 재배치

np.linspace(5,100,20).reshape((4,5)) # 4행 5열로 만든다.

array([[  5.,  10.,  15.,  20.,  25.],
       [ 30.,  35.,  40.,  45.,  50.],
       [ 55.,  60.,  65.,  70.,  75.],
       [ 80.,  85.,  90.,  95., 100.]])

In [ ]:
np.random.rand(2,3) #0에서 1사이의 난수로 초기화

array([[0.53219757, 0.38612696, 0.84402755],
       [0.129737  , 0.29909885, 0.8318244 ]])

In [40]:
np.random.randn(2,3) 
# 표준정규분포를따르는 난수로 초기화
# 표준 정규 분포?

np.random.randn(2,3,5) 

array([[[ 0.35416774,  0.10483799, -0.10783652, -0.23559727,
         -0.12886634],
        [ 1.0720489 ,  2.12592305,  0.22358139, -0.816706  ,
         -0.64094334],
        [-0.21927463, -2.02172482, -0.94322703,  0.83326909,
          0.91297804]],

       [[ 0.74328407,  1.26104514, -0.25127056,  0.41338147,
          0.03663102],
        [ 1.26001455, -0.56373906, -0.76436556,  0.59084284,
          2.62738855],
        [ 1.6741969 ,  1.08233323, -1.18044972, -0.74928819,
          1.03791862]]])

In [47]:
# random.randint(low,high,(size))
np.random.randint(0,101,(3,4)) # 0에서 100까지 난수로 3행 4열

array([[99, 72, 98, 37],
       [84, 12, 81, 22],
       [49, 15, 39, 93]])

In [75]:
np.random.seed(1) 
# 랜덤한 숫자를 초기화할때 시작값을 고정.
# 처음 난수를 생성 -> 재실행 시 그 고정된 값을 영원히 쓴다.
# 시드 값에 대한 설명: 이건 1번시드기때문에 1번시드로 불러오면 늘 같은 1번시드값 뭐그런식인가보다

print(np.random.rand(2,3))
print(np.random.randn(2,2))
print(np.random.randint(0,101,(3,3)))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]
[[-0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387 ]]
[[18 84 11]
 [28 29 14]
 [50 68 87]]


In [ ]:
# rng: 랜덤 넘버 제너레이터
# 최근에 가장 권장되는 방식
from numpy.random import default_rng
rng = default_rng()

print(rng.random((3,2)),"\n")
print(rng.normal(0,1,(4,5)),"\n") # 
print(rng.integers(0,100,(2,2)),"\n")
print(rng.uniform(0,100,(4,4))) # 균등한 분포를 가진 데이터를 일정하게 

[[0.9541511  0.76793209]
 [0.12597075 0.82698809]
 [0.84907207 0.34978284]] 

[[ 0.09375488 -1.17081808 -1.35824039 -1.30656402 -0.71761528]
 [ 1.18562136  0.89453375 -0.54404782 -0.54658792  1.92958774]
 [ 0.90278859 -0.80339058 -0.14971196 -0.43029158  0.15154146]
 [ 0.87914986 -0.27489148  0.36928103  0.56826546  0.78350766]] 

[[12 83]
 [15 89]] 

[[22.79092699 16.36721495 87.83435986 14.64549516]
 [78.95931836 99.42941877  8.15332501 56.66410025]
 [35.19239312 70.91749997 87.99078292 32.21056448]
 [32.7857754  25.0285726  85.10258441 76.48716841]]


0731 실습

In [12]:
# 1번
a=np.zeros((3,4),dtype=np.int64) # 2차원
b=a+5
print(f"1. 0으로 채워진 크기를 5로 :\n{b}\n")
# 2번
a=np.arange(0,21,2)
print(f"2. 0부터 20까지 2씩: {a}\n")
# 3번
from numpy.random import default_rng
rng = default_rng()
a=rng.random((2,3))
print(f"3. 랜덤 0-1 2차원 배열: \n{a}\n")
# 4번
a=np.random.normal(100, 20, 6)
print(f"4. 평균100 표준편차20 정규분포난수 6개: \n{a}\n")
# 5번
a=np.arange(1,21)
b=a.reshape((4,5))
print(f"5. 1-20 1차원배열, 배열을 (4행 5열) 변환: \n{b}\n")

1. 0으로 채워진 크기를 5로 :
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

2. 0부터 20까지 2씩: [ 0  2  4  6  8 10 12 14 16 18 20]

3. 랜덤 0-1 2차원 배열: 
[[0.19788714 0.22919761 0.29026356]
 [0.77417971 0.70816422 0.26771047]]

4. 평균100 표준편차20 정규분포난수 6개: 
[126.82742349  76.56103157  75.80659861  98.76204995 111.59464902
  82.59464614]

5. 1-20 1차원배열, 배열을 (4행 5열) 변환: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]



In [14]:
# 6번
a = np.linspace(0, 1, 12)
b = a.reshape((3, 4))
print(f"6. 0-1 균등간격 12개 값을 (3,4) 크기로 변환:\n{b}\n")

# 7번
a = np.random.randint(0, 100, (10, 10)) # 10x10 난수 배열 생성
b = np.eye(10) # 행과 열이 각각 10인 단위행렬
c = a + b # 더해주기
print(f"7. 0-99 난수 (10,10) 배열 + 단위행렬:\n{c}\n")

# 8번
a = np.random.randint(0, 10, (2, 3, 4))
print(f"8. 0-9 난수 (2,3,4) 3차원 배열:\n{a}")

6. 0-1 균등간격 12개 값을 (3,4) 크기로 변환:
[[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]

7. 0-99 난수 (10,10) 배열 + 단위행렬:
[[53. 97. 45. 46.  2. 40. 40. 16. 85. 96.]
 [72. 76. 21. 66. 22. 19. 91. 61. 26. 19.]
 [16. 93. 44. 14. 11. 13. 67. 11. 76. 53.]
 [29. 64. 89. 24. 67. 74. 90. 72. 99. 79.]
 [49. 56. 50. 76. 26. 21. 96. 72. 53. 68.]
 [81. 67. 91. 68. 81. 42.  0. 43. 65. 42.]
 [90. 31. 58. 41.  2.  9. 77. 26. 51. 46.]
 [23. 78. 74. 45.  0. 56. 37. 17. 10. 61.]
 [91. 22. 64. 78. 61. 73. 80. 73. 29. 78.]
 [59. 64. 44. 75. 91.  0. 41. 81. 71. 97.]]

8. 0-9 난수 (2,3,4) 3차원 배열:
[[[0 2 7 9]
  [1 2 6 6]
  [7 5 6 9]]

 [[5 7 9 2]
  [5 3 0 3]
  [3 2 6 3]]]


# 2025.08.01

In [11]:
# 실습 복습

a1=np.zeros((3,4))
a1_2=np.full((3,4),5)
print(a1,"\n",a1_2)

a2=np.arange(0,21,2)
print("\n",a2)

a3=np.random.rand(2,3)
print("\n",a3)

a4=np.random.normal()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

 [ 0  2  4  6  8 10 12 14 16 18 20]

 [[0.19564284 0.5641446  0.31580601]
 [0.35146108 0.63565459 0.68483863]]


In [29]:
# 인덱싱

a=np.array([10,20,30,40,50,60])

print(a[2])

# 다차원 인덱싱

matrix=[[1,2,3],[4,5,6]] # 2x3 배열
print("파이썬 인덱싱: ",matrix[1][0])

matrix2=np.array([[1,2,3],[4,5,6]])
print("numpy 인덱싱:",matrix2[1,0])

matrix3=np.arange(24).reshape(2,3,4)
print("\n",matrix3)
print("\n17읽기: ",matrix3[1,1,1]) # 3/2/1차원 순으로 읽는다
print("20읽기: ",matrix3[1,2,0])
print("2읽기: ",matrix3[0,0,2])

30
파이썬 인덱싱:  4
numpy 인덱싱: 4

 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

17읽기:  17
20읽기:  20
2읽기:  2


In [35]:
a1=np.array([10,20,30,40,50])
print(a1[1:3])
print(a1[2:])
print(a1[:2])

print(a1[::2])

[20 30]
[30 40 50]
[10 20]
[10 30 50]


In [38]:
py_list=[1,2,3,4,5]
sliced=py_list[1:4] # 새 시퀀스 
print(py_list)
print(sliced)

# 넘파이는 메모리와 공유하고 출력은 view로 보여주고 있기 때문에

[1, 2, 3, 4, 5]
[2, 3, 4]


In [ ]:
# Python 리스트 예제
py_list = [1, 2, 3, 4, 5]
sliced = py_list[1:4]  # [2, 3, 4] 새로운 리스트 생성
sliced[1] = 99         # sliced의 두 번째 요소를 변경

print("원본 리스트:", py_list)     # 변경 없음
print("슬라이스 리스트:", sliced)  # 변경된 값 포함


# NumPy 배열 예제
a1 = np.array([1, 2, 3, 4, 5])
a1_sliced = a1[1:4]     # [2 3 4], 원본과 메모리 공유하는 view
a1_sliced[1] = 100      # a1의 두 번째 인덱스가 변경됨

print("원본 넘파이 배열:", a1)       # 변경된 값 포함
print("슬라이스 배열 (view):", a1_sliced)  # 변경된 값 포함


원본 리스트: [1, 2, 3, 4, 5]
슬라이스 리스트: [2, 99, 4]
원본 넘파이 배열: [  1   2 100   4   5]
슬라이스 배열 (view): [  2 100   4]


In [77]:
a2=np.arange(1,21).reshape(4,5)
print("원본\n",a2)
print("첫 행 슬라이싱\n",a2[0,:]) #0번째 행 다 불러와!!
print("두 행 슬라이싱\n",a2[1]) #1번째 행 다 불러와!!
print("1부터 3행 슬라이싱\n",a2[1:3]) #1부터 3행
print("3행부터 다\n",a2[2:]) #3행부터 다

print("\n------------------------------\n")
print("행을 다 불러왔고, 2번인덱스의 열만출력\n",a2[:,2])
print("행을 다 불러왔고, 1,2번인덱스의 열만출력\n이 경우 2차원배열 형태 유지\n",a2[:,1:3])
print("1~2번째 행, 2~3번째 열의 직사각형 영역 추출\n",a2[1:3, 2:4])

원본
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
첫 행 슬라이싱
 [1 2 3 4 5]
두 행 슬라이싱
 [ 6  7  8  9 10]
1부터 3행 슬라이싱
 [[ 6  7  8  9 10]
 [11 12 13 14 15]]
3행부터 다
 [[11 12 13 14 15]
 [16 17 18 19 20]]

------------------------------

행을 다 불러왔고, 2번인덱스의 열만출력
 [ 3  8 13 18]
행을 다 불러왔고, 1,2번인덱스의 열만출력
이 경우 2차원배열 형태 유지
 [[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]
1~2번째 행, 2~3번째 열의 직사각형 영역 추출
 [[ 8  9]
 [13 14]]


In [85]:
a3=np.arange(36).reshape(3,3,4)
print(a3,"\n")

print("17,18 선택:\n ",a3[1,1,1:3]) # 바깥에서부터 하나씩 더듬떠듬 찾아가자.

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]] 

17,18 선택:
  [17 18]


In [90]:
a1 = np.array([1, 2, 3])
a1_copied = a1.view() # 얕은 복사
a1_copied[1] = 10

print("origin", a1)
print("copied", a1_copied) # 원본을 해친다

a2=np.array([1,2,3])
a2_copied=a2.copy() # 깊은 복사
a2_copied[1]=10

print("origin", a2)
print("copied", a2_copied) # 원본을 해치지 않는다


origin [ 1 10  3]
copied [ 1 10  3]
origin [1 2 3]
copied [ 1 10  3]


In [113]:
# 팬시 인덱싱
af=np.arange(1,21)
print("origin\n",af)
print("sliced\n",af[[4,7,11]],"\n") # 정수배열 인덱싱. 여러요소를 한번에 선택

# 팬시 인덱싱
af2=np.arange(1,21).reshape(4,5)
print("origin\n",af2)
print("sliced\n",af2[[1,3],[2,4]]) # 1.2 와 3.4를 고름



origin
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
sliced
 [ 5  8 12] 

origin
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
sliced
 [ 8 20]


In [104]:
# 불리언 인덱싱
ab=np.linspace(10,100,10) #10에서 100까지 10단위로 10개
print(ab)
print(ab[ab>40]) # 40보다 큰 것만 자른다

# 불리언 마스킹
ab2=np.arange(0,21)
mask=ab2%2==0 
print(ab2[mask]) #배열에서 원소를 조건에따라 추출

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 50.  60.  70.  80.  90. 100.]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [136]:
# 실습목록

arr=np.arange(10,30,2)
print(arr[[1,3,5]],"\n")

arr=np.arange(1,10).reshape(3,3)
print(arr)
print(f"159선택: {arr[0,0]},{arr[1,1]},{arr[2,2]}\n")

arr=np.arange(1,13).reshape(3,4)
print(arr,"\n")

[12 16 20] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
159선택: 1,5,9

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



In [ ]:
# 실습목록

arr=np.arange(10,30,2)
print(arr[[1, 3, 5]], "\n")

arr=np.arange(1,10).reshape(3,3)
print(arr)
print(f"159선택: {arr[0,0]},{arr[1,1]},{arr[2,2]}\n")

arr=np.arange(1,13).reshape(3,4)
print(arr)
arr[:, -1] = -1
print(arr, "\n")

arr=np.arange(1,17).reshape(4,4)
print(arr)
print(arr[::-1, :])
print(arr[:, ::-1], "\n")

arr=np.arange(1,21).reshape(4,5)
print(arr)
middle = arr[1:3, 1:4].copy()
print(middle, "\n")

arr=np.array([[ 4,  9, 12,  7], 
               [10, 15, 18,  3], 
               [ 2, 14,  6, 20]])
print(arr)
print(arr[(arr%2==0) & (arr>=10)])



[12 16 20] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
159선택: 1,5,9

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3 -1]
 [ 5  6  7 -1]
 [ 9 10 11 -1]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8  9]
 [12 13 14]] 

[[ 4  9 12  7]
 [10 15 18  3]
 [ 2 14  6 20]]
[12 10 18 14 20]


실습3. NumPy 종합 연습(1)
1. 0부터 24까지 정수를 가진 배열을 만들고, (5, 5) 배열로 변환한 뒤 가운데 행(3번째 행)과 가
운데 열(3번째 열)을 각각 1차원 배열로 출력하세요.
2. 0~99 난수로 이루어진 (10, 10) 배열을 생성하고,
짝수 인덱스의 행만 선택하여 출력하세요.
3. 0부터 49까지 정수를 가진 배열을 (5, 10) 배열로 변환한 후, 2행 3열부터 4행 7열까지의 부
분 배열을 추출하세요.

4. 0~9 난수로 이루어진 (4, 4) 배열을 생성하고, 각각 인덱싱으로 추출해 출력하세요.(for 이용)
- 주대각선 요소 (왼쪽 위 → 오른쪽 아래)
- 부대각선 요소 (오른쪽 위 → 왼쪽 아래)
5. 0~9 난수로 이루어진 (3, 4, 5) 3차원 배열을 생성하고, 두 번째 층에서 첫 번째 행과 마지막
열의 값을 출력하세요.

6. 35부터 74까지의 순차적인 수로 이루어진 1차원 배열을 만들고 10x4 행렬로 변환 후 출력해
주세요.
7. 6번에서 만든 배열을 맨 끝의 행부터 역순으로 출력해주세요.
8. 6번에서 만든 배열 중 두 번째 행부터 마지막 직전 행까지, 세번째 열부터 마지막 열까지 슬라
이싱해서 출력해주세요.

9. 1부터 50까지의 난수로 된 5x6 배열을 만들고, 배열에서 짝수만 선택하여 출력하는 코드를
작성하세요.
10. 0부터 99까지의 정수로 이루어진 (10, 10) 배열을 생성한 후,
[1, 3, 5]번째 행과 [2, 4, 6]번째 열의 교차하는 원소들만 선택하여 출력하세요.
11. 0~9 난수로 이루어진 1차원 배열(길이 15)을 생성하고,
짝수 인덱스 위치에 있는 값들 중에서 5 이상인 값만 선택해 출력하세요.

In [ ]:
# 실습1
a=np.arange(0,25).reshape(5,5)
print("전체\n",a)
print("가운데행",a[2])
print("가운데열",a[:,2])



전체
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
가운데행 [10 11 12 13 14]
가운데열 [ 2  7 12 17 22]


In [167]:
# 함께 정리하기
a=np.arange(0,25).reshape(5,5)
print("전체\n",a)
print("가운데행",a[2])
print("가운데열",a[:,2])

a2=np.random.randint(0,100,(10,10))
print("100 이하 정수난수:\n",a2[::2])

a3=np.arange(50).reshape(5,10)
print("2행3열부터 4행7열까지 부분배열\n",a3[1:4,2:8])

a4=np.random.randint #추후 수정


전체
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
가운데행 [10 11 12 13 14]
가운데열 [ 2  7 12 17 22]
100 이하 정수난수:
 [[40 99 44 32 26 15 55 52 46 93]
 [41 20 43 41 44 12 67 33 41  1]
 [ 6 69 58 11 21 25 91 96 70 15]
 [65 62 62 83 43 20 24 99 83 65]
 [80 14 32 93  1 16 38 90 84 47]]
2행3열부터 4행7열까지 부분배열
 [[12 13 14 15 16 17]
 [22 23 24 25 26 27]
 [32 33 34 35 36 37]]


In [172]:
a5=np.random.randint(0,10,(3,4,5))
print(a5)
print(a5[1,0,-1])

[[[4 0 2 4 9]
  [8 9 9 8 1]
  [2 7 6 3 9]
  [6 8 1 9 7]]

 [[1 4 7 7 2]
  [0 2 0 1 1]
  [8 2 8 5 3]
  [6 9 3 7 5]]

 [[7 8 9 7 2]
  [2 6 0 3 5]
  [2 6 9 1 8]
  [2 9 9 1 5]]]
2


In [4]:
import numpy as np
import random as r

In [6]:
a6= np.arange(35,75).reshape(10,4)
print(a6)

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]


In [ ]:
a7=a6[::-1] # 행 역순
print(a7)

[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]


In [18]:
a8=a6[1:-1,2:] 
# 두번째행, 마지막행 빼고 자르기
# 세번째 열, 마지막 열까지
print(a8)

[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [32]:
arr=np.random.randint(1,51,(5,6))
print(arr)

a9=arr[arr%2==0] # 불리언 인덱싱. 대괄호 안 조건에 트루펄스 맞춰서 리스트
mask=arr%2==0
print("짝수만: ",a9) # 짝수만 골라서 출력. 트루인 조건의 요소만 출력
print(mask)

[[27 17 23 34 29  2]
 [42 44 31 31 49 28]
 [27 18  5 18  4 22]
 [31 15 34  8 47 34]
 [18 42 43 19 17 47]]
짝수만:  [34  2 42 44 28 18 18  4 22 34  8 34 18 42]
[[False False False  True False  True]
 [ True  True False False False  True]
 [False  True False  True  True  True]
 [False False  True  True False  True]
 [ True  True False False False False]]


In [ ]:
arr=np.arange(100).reshape(10,10)
selected_row=arr[[1,3,5]]
print(selected_row,"\n")
selected_col=selected_row[:,[2,4,6]]
print(selected_col,"\n") # 1,3,5 열의 2,4,6 행을 고르다.
print(arr)

[[10 11 12 13 14 15 16 17 18 19]
 [30 31 32 33 34 35 36 37 38 39]
 [50 51 52 53 54 55 56 57 58 59]] 

[[12 14 16]
 [32 34 36]
 [52 54 56]] 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [38]:
# 위의 것을 한줄로?
arr=np.arange(100).reshape(10,10)
a10=arr[[1,3,5]][:,[2,4,5]]
print(a10)

[[12 14 15]
 [32 34 35]
 [52 54 55]]


In [45]:
arr=np.random.randint(0,10,15) #0-9범위 내 난수로 15길이의 리스트 생성
print(arr)

even_idx=arr[::2]
print(even_idx) #짝수 인덱스에 위치한 값들
a11=even_idx[even_idx>=5] # 5 이상 출력

[2 8 6 8 2 3 0 4 0 0 7 6 9 2 7]
[2 6 2 0 0 7 9 7]


# 넘파이 배열연산
#### 2025.08.04
##### 요소 단위로 수행되는 배열연산

In [46]:
import numpy as np

In [52]:
# 요소끼리 더해지는 행렬간 연산

a1=np.array([1,2,3])
a2=np.array([4,5,6])

print(a1+a2)

# 배열과 배열간, 혹은 배열과 스칼라값 간의 연산을 지원
# 브로드캐스팅으로 서로 다른 크기의 연산도 자동확장 가능


[5 7 9]


In [71]:
# 2차원 연산
a1=np.arange(1,5).reshape(2,2)
a2=np.arange(11,15).reshape(2,2)
print(f">> a1 배열과 a2배열 \n{a1}\n{a2}\n")
print(f">> a1+a2\n{a1+a2}\n")
print(f">> a2-a1\n{a2-a1}\n")

# 배열과 스칼라간의 연산
print(f">> a1 * 10, 배열과 스칼라 연산\n{a1*10}")


>> a1 배열과 a2배열 
[[1 2]
 [3 4]]
[[11 12]
 [13 14]]

>> a1+a2
[[12 14]
 [16 18]]

>> a2-a1
[[10 10]
 [10 10]]

>> a1 * 10, 배열과 스칼라 연산
[[10 20]
 [30 40]]


In [76]:
# 서로 크기가 다른 배열간의 연산, 브로드캐스팅
# 브로드캐스팅 - 배열의 크기를 확장해 서로 다른 배열간 연산을 가능케 함.


a1=np.array([[1,2,3],
             [4,5,6]]) 
            # 2x3 배열

a2=np.array([10,20,30]) 
            # 길이가 3인 배열

#1차원 길이
[10,20,30]
# 2차원으로 변형
[[10,20,30]]
# 2차원의 행이 2로 확장
[[10,20,30],
 [10,20,30]]
# 이렇게 변형된 a2배열을
# a1배열과 더하게 된다.

print(a1+a2)


[[11 22 33]
 [14 25 36]]


In [87]:
a1=np.array([[1],[2],[3]])
print(a1)
a2=np.array([10,20,30])
print(a2)
print()


# 2차원의 경우: 3vs1>> a2의 2차원이 3으로 확장?
[[10,20,30],[10,20,30],[10,20,30]]

# 1차원이 경우: a1의 1차원이 3으로 확장
[[1,1,1],[2,2,2],[3,3,3]]

print(a1+a2)

# 한쪽이 차원이 1인 경우만 확장이 가능하다

[[1]
 [2]
 [3]]
[10 20 30]

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [126]:
# 실습1
arr1=np.array([1,2,3,4])
print(arr1+3)

arr2=np.array([[5,10],
               [15,20]])
arr2_new=arr2*-1
print(arr2_new)

arr3_1=np.array([2,4,6])
arr3_2=np.array([1,2,3])
print(f"곱:\n{arr3_1*arr3_2}\n나눗셈:\n{arr3_1//arr3_2}")

arr4=np.array([[95,97],
               [80,85]])
                # 5,3,20,15
arr4_add=np.array([100-arr4])
print(f"실습4\n{arr4+arr4_add}")

arr5 = np.array([[1, 2, 3],
                [4, 5, 6]])
arr5_mul=np.array([[10],[100]])
print(f"실습5\n{arr5*arr5_mul}")

arr6=np.array([[10,20],
               [30,40],
               [50,60]])
arr6_add=np.array([[100],[200],[300]])
print(f"실습6\n{arr6+arr6_add}")


[4 5 6 7]
[[ -5 -10]
 [-15 -20]]
곱:
[ 2  8 18]
나눗셈:
[2 2 2]
실습4
[[[100 100]
  [100 100]]]
실습5
[[ 10  20  30]
 [400 500 600]]
실습6
[[110 120]
 [230 240]
 [350 360]]
