### 통계 함수 및 집계연산

In [2]:
import numpy as np

In [32]:
a=np.array([[1,2,3],[4,5,6]])

print("통게 및 집계연산")
print("numpy행렬 원소의 합:",np.sum(a))
print("원소의 평균: ",np.mean(a))
print("표준편차: ",np.std(a))
print("최대값: ",np.max(a))
print("최소값: ",np.min(a))
print("최대값 인덱스: ",np.argmax(a))
print("최소값 인덱스: ", np.argmin(a))

통게 및 집계연산
numpy행렬 원소의 합: 21
원소의 평균:  3.5
표준편차:  1.707825127659933
최대값:  6
최소값:  1
최대값 인덱스:  5
최소값 인덱스:  0


In [27]:
print("축 단위 연산")
# 특정한 축을 기준으로 연산을 하겠다는 의미
# axis = 0 >>> 가장 높은 차원 기준.
# axis = 1 >>> 그 다음 차원 기준.

a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

print(a.shape)
print("2 = axis0, 3 = axis1")
print("axis 0: 행기준, axis 1: 열기준\n")

print("행기준 합",np.sum(a,axis=0))
# 0.0(1)+1.0(4)=5
# 0.1(2)+1.1(5)=7 이런식으로 연산
print("열기준 합",np.sum(a,axis=1),"\n")
# 0.0(1)+(0.1)(2)+0.2(3)=6
# 이런 식으로 연산

print("행기준 평균",np.mean(a,axis=0)) # 4,5,6
print("열기준 평균",np.mean(a,axis=1)) # 2,5,8

# 행기준: 행을 따라 연산한다. 행인덱스를 증가시키며 연산한다.
# 열기준: 열을 따라 연산한다. 열인덱스를 증가시키며 연산한다.

축 단위 연산
(3, 3)
2 = axis0, 3 = axis1
axis 0: 행기준, axis 1: 열기준

행기준 합 [12 15 18]
열기준 합 [ 6 15 24] 

행기준 평균 [4. 5. 6.]
열기준 평균 [2. 5. 8.]


In [30]:
print("누적 연산")
arr=np.array([1,2,3,4])
print(np.cumsum(arr)) # (더하기) 순서대로 누적하며 연산결과를 저장한다
print(np.cumprod(arr)) # (곱하기) 순서대로 누적하며 연산결과를 저장한다

누적 연산
[ 1  3  6 10]
[ 1  2  6 24]


In [6]:
# 실습2

#1
arr=np.array([5,10,15,20])
print(f"평균: {np.mean(arr)}\n합계: {np.sum(arr)}\n")
#2
arr=np.array([[3,7,1],
              [9,2,8]])
print(f"전체 최솟값: {np.argmax(arr)}\n최대값: {np.argmax(arr)}\n")
#3
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(f"열의 합계(행기준): {np.sum(arr,axis=0)}\n행의 합계(열기준):{np.sum(arr,axis=1)}\n")
#4
arr=np.array([[10,20],
              [30,40],
              [50,60]])
print(f"열별 평균(행기준): {np.mean(arr,axis=0)}\n행별 평균(열기준): {np.mean(arr,axis=1)}\n")
#5
arr=np.array([2,4,4,4,5,5,7,9])
arr_far=arr-np.mean(arr)
print(f"표준편차: {np.std(arr)} | 얼마나 떨어져있나?: {arr_far}\n")
#6
arr=np.array([[1,2,3],
             [4,5,6]])
print(f"원본배열\n{arr}\n행 단위 누적합:\n {np.cumsum(arr,axis=0)}\n열 단위 누적곱: \n{np.cumprod(arr,axis=1)}")

평균: 12.5
합계: 50

전체 최솟값: 3
최대값: 3

열의 합계(행기준): [12 15 18]
행의 합계(열기준):[ 6 15 24]

열별 평균(행기준): [30. 40.]
행별 평균(열기준): [15. 35. 55.]

표준편차: 2.0 | 얼마나 떨어져있나?: [-3. -1. -1. -1.  0.  0.  2.  4.]

원본배열
[[1 2 3]
 [4 5 6]]
행 단위 누적합:
 [[1 2 3]
 [5 7 9]]
열 단위 누적곱: 
[[  1   2   6]
 [  4  20 120]]


# 논리연산과 조건연산

In [14]:
# np.where() 조건 기반 선택함수
arr=np.array([10,20,30,40,50,60,70,80,90,100])
result=np.where(arr>50,"high","low")
                        # 참일경우,거짓일경우
                        # 참일 경우 high, 거짓일경우 log 할당
print(result)

arr=np.array([10,20,30,40,50,60,70,80,90,100])
result=np.where(arr>50)
print(arr[result]) # 조건만 넣을 경우 조건만족하는 원소의 '인덱스' 만 반환한다.
                # 팬시 인덱싱으로 정리

['low' 'low' 'low' 'low' 'low' 'high' 'high' 'high' 'high' 'high']
[ 60  70  80  90 100]


In [21]:
# 논리연산
# and:&, or:|, not:~

# and 연산
arr=np.array([10,20,30,40,50,60,70,80,90,100])
mask=(arr>10)&(arr<80)
print("& 연산",arr[mask])

# or 연산
mask_or=(arr==10) | (arr==100)
print("or 연산",arr[mask_or])

# not 연산
mask_not=~(arr > 30)
print("~연산",arr[mask_not])

& 연산 [20 30 40 50 60 70]
or 연산 [ 10 100]
~연산 [10 20 30]


In [24]:
arr=np.arange(0,101)
mask=(arr%2==0) & (arr>90)
print(arr[mask])

[ 92  94  96  98 100]


In [85]:
# 실습3
#1
arr=np.array([5,12,18,7,30,25])
print(arr[(arr>10)&(arr<20)])
#2
arr=np.array([10,15,20,25,30,35])
print(arr[(arr<15)|(arr>30)])
#3
arr=np.array([3,8,15,6,2,20])
arr=np.where(arr>10,0,arr)
print(arr)
#4
arr=np.array([7,14,21,28,35])
arr_new=np.where(arr>20,"high","low")
print(arr_new)
#5
arr=np.arange(0,10)
arr_new=np.where(arr%2==0,arr,arr*10)
print(arr_new)
#6
arr=np.array([[10,25,30],
              [40,5,15],
              [20,35,50]])
print(arr[np.where((arr>20)&(arr<40))])
#7
arr=np.arange(1,7)
print(arr[np.where(arr%3!=0)])
#8
arr=np.random.randint(0,100,10)
arr_new=np.where(arr>50,arr,50)
print(f"랜덤정수배열: {arr}\n50이상은 그대로, 미만은 50화: {arr_new}")
#9
arr=np.array([[5,50,94],
              [20,75,10],
              [60,30,85]])

result = np.where(arr > 70, "A",
         np.where(arr >= 30, "B", "C"))
print(result)

[12 18]
[10 35]
[3 8 0 6 2 0]
['low' 'low' 'high' 'high' 'high']
[ 0 10  2 30  4 50  6 70  8 90]
[25 30 35]
[1 2 4 5]
랜덤정수배열: [55 29 89 35 63 15 84 44 72 24]
50이상은 그대로, 미만은 50화: [55 50 89 50 63 50 84 50 72 50]
[['C' 'B' 'A']
 ['C' 'A' 'C']
 ['B' 'B' 'A']]


# 2025.08.05
# 행렬의 곱

In [1]:
import numpy as np

In [ ]:
# 2x3 행렬과 3x2행렬의 연산
# 앞 행렬의 열의 개수=뒤행렬의 행의 개수
# 그래야만 곱연셈이 가능하다. 
# 같지 않으면 계산 자체가 성립이 안됨!!!

# 내적? : 같은 위치의 숫자를

a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([[6,3],
            [5,2],
            [4,1]])
print(np.dot(a,b),"\n")


a=np.array([[2,2,2],
            [5,5,5]])

b=np.array([[10,3],
            [10,3],
            [10,3]])

# 같은 위치의 숫자를 곱하고 모두 더한다
print(a@b)

[[28 10]
 [73 28]] 

[[ 60  18]
 [150  45]]


In [16]:
c=np.array([1000,2000,5000,10000])
d=np.array([10,3,5,7])
# 같은 위치에 있는 값끼리 곱하고 나중에 더한다.
# => 내적연산.
print(c@d)
print(np.matmul(c,d))

# dot과의 차이?
# 이름이 다르고 스칼라연산이 안되는 점.

111000
111000


In [24]:
# 2차원 배열간 연산 > 행렬곱셈
a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([[1,2],
            [3,4],
            [5,6]])
print(np.matmul(a,b),"\n")

c=np.array([[1,2],[3,4]])
d=np.array([5,6])
print(np.matmul(c,d),"\n")
print(np.matmul(d,c),"\n")

e=np.array([[1,2,3]])
f=np.array([[1,2],[3,4],[5,6]])
print(np.matmul(e,f))


[[22 28]
 [49 64]] 

[17 39] 

[23 34] 

[[22 28]]


In [56]:
# 실습
#1
a=np.random.randint(1,10,9).reshape(3,3)
b=np.full(6,2).reshape(3,2)
print(np.dot(a,b),"\n")
#2
i=np.eye(4,4)
m=np.random.randint(0,10,16).reshape(4,4)
print("oirignal m\n",m)
print("after matmul with i\n",np.matmul(i,m),"\n")
#3
x=np.full(10,1).reshape(2,5)
y=np.arange(5,15).reshape(5,2)
print(x@y,"\n")
#4
c=np.random.randint(0,5,6).reshape(3,2)
d=np.random.randint(0,5,6).reshape(2,3)
cd=c@d
print(cd,cd.shape)

[[20 20]
 [28 28]
 [38 38]] 

oirignal m
 [[6 2 6 7]
 [1 4 6 7]
 [7 2 1 1]
 [5 1 9 5]]
after matmul with i
 [[6. 2. 6. 7.]
 [1. 4. 6. 7.]
 [7. 2. 1. 1.]
 [5. 1. 9. 5.]] 

[[45 50]
 [45 50]] 

[[ 4  8  5]
 [16 11 13]
 [12 12 11]] (3, 3)


In [ ]:
a=np.array([[1,2,3],[4,5,6]])

#axis0
# 차원 확장하는 expand_dims
a0=np.expand_dims(a,axis=0)
print("오리지널:\n",a.shape,"\n",a)
print("a0 shape:\n",a0.shape,"\n겹이하나 추가됨\n",a0)

a1=np.expand_dims(a,axis=1) # 1번째 인덱스에 추가한다.
print("a1 shape:\n",a1.shape,"\n1번 자리에 추가됨\n",a1)

오리지널:
 (2, 3) 
 [[1 2 3]
 [4 5 6]]
a0 shape:
 (1, 2, 3) 
겹이하나 추가됨
 [[[1 2 3]
  [4 5 6]]]
a1 shape:
 (2, 1, 3) 
1번 자리에 추가됨
 [[[1 2 3]]

 [[4 5 6]]]


In [ ]:
my_list=[1,2,3,4]
my_list.insert(2,10)
print(my_list)
print("insert는 들어갈 위치의 인덱스를 써준다.")
print("dim 역시 마찬가지로 들어갈 행의 인덱스에 axis 사용한다.")

[1, 2, 10, 3, 4]
insert는 들어갈 위치의 인덱스를 써준다.
dim 역시 마찬가지로 들어갈 행의 인덱스에 axis 사용한다.


In [76]:
# np.squeeze( 차원축소 )
# 배열에서 크기가 1인 차원을 제거하는 함수
a=np.array([[[[1],[2],[3]]]])
print(a)
print(a.shape,"\n")
s=np.squeeze(a) #axis 지정않고 스퀴즈시
print(s) # 1인 차원이 모두 제거된다.
print(s.shape)

[[[[1]
   [2]
   [3]]]]
(1, 1, 3, 1) 

[1 2 3]
(3,)


In [81]:
a2=np.zeros((1,4,1,2))
print(a2.shape)

s1=np.squeeze(a2,axis=0)
print(s1.shape) # 0 축만 제거

s2=np.squeeze(a2,axis=2)
print(s2.shape) 

(1, 4, 1, 2)
(4, 1, 2)
(1, 4, 2)


In [84]:
a=np.array([1,1,1,5,5,2,2,2,2,4,4,4,3,3,3])
u1=np.unique(a)
print(u1)

u2, idx, inv, cnt=np.unique(a, return_index=True, return_inverse=True,return_counts=True)
print("인덱스: ",idx) # 고유값이 원본에서 처음 나타나는 인덱스
print("원본 고유값 인덱스:",inv)
print("값 등장 횟수: ", cnt)

[1 2 3 4 5]
인덱스:  [ 0  5 12  9  3]
원본 고유값 인덱스: [0 0 0 4 4 1 1 1 1 3 3 3 2 2 2]
값 등장 횟수:  [3 4 3 3 2]


In [116]:
#1
arr=np.array([[10,20],[30,40],[50,60]])
arv=np.ravel(arr) # 원본의 변경사항에 영향을 받는다
aft=arr.flatten()
print(arv)
print(aft,"\n")
#2
img=np.random.rand(32,32)
ex_img=np.expand_dims(img,axis=0)
print(ex_img.shape,"\n")
#3
img=np.random.randint(0,255,(1,28,28,1))
sq_img=np.squeeze(img)
print(sq_img.shape,"\n")
#4
arr=np.array([[3,1,2,2],
              [1,2,3,1],
              [2,2,1,4]])
arr=arr.flatten()
arr=np.unique(arr)
print(arr.reshape(1,-1),"\n")
#5
arr = np.array([[[1], [3], [2], [1], [3], [2], [3], [1], [2], [3]]])
arr=arr.squeeze(axis=0)
print(arr.shape)
print(np.unique(arr),"\n")
#6
arr = np.array([ [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]],
[[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]] ]) 
arr=arr.squeeze()
arr=np.unique(arr)
arr=np.expand_dims(arr,axis=1) #뒤에 차원을 추가한다...
print(arr.reshape(9,1))
print(arr.shape)

[10 20 30 40 50 60]
[10 20 30 40 50 60] 

(1, 32, 32) 

(28, 28) 

[[1 2 3 4]] 

(10, 1)
[1 2 3] 

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(9, 1)


# 배열 결합과 분리

In [121]:
# 배열 시퀀스를 결합해주는 concatenate

a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
ab=np.concatenate((a,b),axis=0) #행방향 결합
print(ab,"\n")

c=np.array([[7],[8],[9]])
abc=np.concatenate((ab,c),axis=1) #열방향 결합
# 결합이 불가한 경우: 결합하는 axis를 제외한 나머지 차원이 같지 않을 경우
print(abc)

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [124]:
# stack
a=np.array([1,2,3])
b=np.array([4,5,6])

ab_stack=np.stack((a,b),axis=0)
print(ab_stack,"\n")

ab_stack2=np.stack((a,b),axis=1)
print(ab_stack2)

[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]]


In [126]:
# hstack, vstack
a=np.array([1,2,3])
b=np.array([4,5,6])

ab_stack=np.hstack((a,b))
print(ab_stack,"\n")

a=np.array([[1],[2],[3]])
b=np.array([[4],[5],[6]])
ab_stack2=np.vstack((a,b))
print(ab_stack2)

[1 2 3 4 5 6] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [137]:
# split 여러개의 하위배열로 분할
a=np.arange(9)
s=np.split(a,3)
print(s,"\n") # 같은 크기로만 나눌 수 있음.

a=np.arange(16).reshape(4,4)
print(a,"\n")

s1=np.split(a,[1,3])
for part in s1:
    print(part)

print("")

s2=np.split(a,2,axis=1)
for part in s2:
    print(part)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
#1
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
ab=np.concatenate((a,b),axis=0)
print(ab)
#2
a=np.arange(12)
a=np.split(a,4)
print(a)
#3
a=np.array([1,2])
b=np.array([3,4])
c=np.array([5,6])
abc=np.stack((a,b,c),axis=0)
print(abc)

[[1 2]
 [3 4]
 [5 6]]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]
[[1 2]
 [3 4]
 [5 6]]


# 배열의 정렬

In [161]:
#np.sort(arr)
#복사본 반환
#arr.sort()
#원본배열을 정렬

a=np.array([3,1,2,8,5])
s=np.sort(a)
print(f"a 배열          : {a}")
print(f"s=np.sort()    : {s}")
print(f"a.sort() 작업중...")
a.sort()
print(f"a 배열          : {a}")



a 배열          : [3 1 2 8 5]
s=np.sort()    : [1 2 3 5 8]
a.sort() 작업중...
a 배열          : [1 2 3 5 8]


In [ ]:
# 2차원배열의경우?
a=[[6,5,4],[3,1,2]]
s=np.sort(a)
print(f"a 배열          : {a}")
print(f"s=np.sort()    : \n{s}\n")

print(f"a.sort() 작업중...")
a.sort()
print(f"a 배열          : {a}")

a 배열          : [[6, 5, 4], [3, 1, 2]]
s=np.sort()    : 
[[4 5 6]
 [1 2 3]]

a.sort() 작업중...
a 배열          : [[3, 1, 2], [6, 5, 4]]


In [168]:
a=[[6,5,4],[3,1,2]]
s=np.sort(a,axis=0)
print(s)
print("행을 비교해서 정렬한다.")
a=[[6,5,4],[3,1,2]]
s=np.sort(a,axis=1)
print(s)
print("열을 비교해서 정렬한다.")


[[3 1 2]
 [6 5 4]]
행을 비교해서 정렬한다.
[[4 5 6]
 [1 2 3]]
열을 비교해서 정렬한다.


In [173]:
a=np.array([3,1,4,2])
idx=np.argsort(a)
print(idx)
print("소트된 값의 인덱스 값을 반환")
print(a[idx]) #idx의 인덱스 값으로 출력

[1 3 0 2]
소트된 값의 인덱스 값을 반환
[1 2 3 4]


In [185]:
#1
arr=np.array([7,2,9,4,5])
arr.sort()
arr2=arr
print(arr,"\n",arr[::-1],"\n") # 뒤집기 빠먹었다..
#2
arr=np.array([[9,2,5],
              [3,8,1]])
s=np.sort(arr,axis=1)
print(s,"\n")
#3
arr=np.array([10,3,7,1,9])
idx=np.argsort(arr)
print(arr[idx],"\n")
#4
arr=np.array([[4,7,2],
              [9,1,5],
              [6,8,3]])
s=np.sort(arr,axis=0)
print(s)

[2 4 5 7 9] 
 [9 7 5 4 2] 

[[2 5 9]
 [1 3 8]] 

[ 1  3  7  9 10] 

[[4 1 2]
 [6 7 3]
 [9 8 5]]
