### 통계 함수 및 집계연산

In [2]:
import numpy as np

In [32]:
a=np.array([[1,2,3],[4,5,6]])

print("통게 및 집계연산")
print("numpy행렬 원소의 합:",np.sum(a))
print("원소의 평균: ",np.mean(a))
print("표준편차: ",np.std(a))
print("최대값: ",np.max(a))
print("최소값: ",np.min(a))
print("최대값 인덱스: ",np.argmax(a))
print("최소값 인덱스: ", np.argmin(a))

통게 및 집계연산
numpy행렬 원소의 합: 21
원소의 평균:  3.5
표준편차:  1.707825127659933
최대값:  6
최소값:  1
최대값 인덱스:  5
최소값 인덱스:  0


In [27]:
print("축 단위 연산")
# 특정한 축을 기준으로 연산을 하겠다는 의미
# axis = 0 >>> 가장 높은 차원 기준.
# axis = 1 >>> 그 다음 차원 기준.

a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

print(a.shape)
print("2 = axis0, 3 = axis1")
print("axis 0: 행기준, axis 1: 열기준\n")

print("행기준 합",np.sum(a,axis=0))
# 0.0(1)+1.0(4)=5
# 0.1(2)+1.1(5)=7 이런식으로 연산
print("열기준 합",np.sum(a,axis=1),"\n")
# 0.0(1)+(0.1)(2)+0.2(3)=6
# 이런 식으로 연산

print("행기준 평균",np.mean(a,axis=0)) # 4,5,6
print("열기준 평균",np.mean(a,axis=1)) # 2,5,8

# 행기준: 행을 따라 연산한다. 행인덱스를 증가시키며 연산한다.
# 열기준: 열을 따라 연산한다. 열인덱스를 증가시키며 연산한다.

축 단위 연산
(3, 3)
2 = axis0, 3 = axis1
axis 0: 행기준, axis 1: 열기준

행기준 합 [12 15 18]
열기준 합 [ 6 15 24] 

행기준 평균 [4. 5. 6.]
열기준 평균 [2. 5. 8.]


In [30]:
print("누적 연산")
arr=np.array([1,2,3,4])
print(np.cumsum(arr)) # (더하기) 순서대로 누적하며 연산결과를 저장한다
print(np.cumprod(arr)) # (곱하기) 순서대로 누적하며 연산결과를 저장한다

누적 연산
[ 1  3  6 10]
[ 1  2  6 24]


In [6]:
# 실습2

#1
arr=np.array([5,10,15,20])
print(f"평균: {np.mean(arr)}\n합계: {np.sum(arr)}\n")
#2
arr=np.array([[3,7,1],
              [9,2,8]])
print(f"전체 최솟값: {np.argmax(arr)}\n최대값: {np.argmax(arr)}\n")
#3
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(f"열의 합계(행기준): {np.sum(arr,axis=0)}\n행의 합계(열기준):{np.sum(arr,axis=1)}\n")
#4
arr=np.array([[10,20],
              [30,40],
              [50,60]])
print(f"열별 평균(행기준): {np.mean(arr,axis=0)}\n행별 평균(열기준): {np.mean(arr,axis=1)}\n")
#5
arr=np.array([2,4,4,4,5,5,7,9])
arr_far=arr-np.mean(arr)
print(f"표준편차: {np.std(arr)} | 얼마나 떨어져있나?: {arr_far}\n")
#6
arr=np.array([[1,2,3],
             [4,5,6]])
print(f"원본배열\n{arr}\n행 단위 누적합:\n {np.cumsum(arr,axis=0)}\n열 단위 누적곱: \n{np.cumprod(arr,axis=1)}")

평균: 12.5
합계: 50

전체 최솟값: 3
최대값: 3

열의 합계(행기준): [12 15 18]
행의 합계(열기준):[ 6 15 24]

열별 평균(행기준): [30. 40.]
행별 평균(열기준): [15. 35. 55.]

표준편차: 2.0 | 얼마나 떨어져있나?: [-3. -1. -1. -1.  0.  0.  2.  4.]

원본배열
[[1 2 3]
 [4 5 6]]
행 단위 누적합:
 [[1 2 3]
 [5 7 9]]
열 단위 누적곱: 
[[  1   2   6]
 [  4  20 120]]


# 논리연산과 조건연산

In [14]:
# np.where() 조건 기반 선택함수
arr=np.array([10,20,30,40,50,60,70,80,90,100])
result=np.where(arr>50,"high","low")
                        # 참일경우,거짓일경우
                        # 참일 경우 high, 거짓일경우 log 할당
print(result)

arr=np.array([10,20,30,40,50,60,70,80,90,100])
result=np.where(arr>50)
print(arr[result]) # 조건만 넣을 경우 조건만족하는 원소의 '인덱스' 만 반환한다.
                # 팬시 인덱싱으로 정리

['low' 'low' 'low' 'low' 'low' 'high' 'high' 'high' 'high' 'high']
[ 60  70  80  90 100]


In [21]:
# 논리연산
# and:&, or:|, not:~

# and 연산
arr=np.array([10,20,30,40,50,60,70,80,90,100])
mask=(arr>10)&(arr<80)
print("& 연산",arr[mask])

# or 연산
mask_or=(arr==10) | (arr==100)
print("or 연산",arr[mask_or])

# not 연산
mask_not=~(arr > 30)
print("~연산",arr[mask_not])

& 연산 [20 30 40 50 60 70]
or 연산 [ 10 100]
~연산 [10 20 30]


In [24]:
arr=np.arange(0,101)
mask=(arr%2==0) & (arr>90)
print(arr[mask])

[ 92  94  96  98 100]


In [85]:
# 실습3
#1
arr=np.array([5,12,18,7,30,25])
print(arr[(arr>10)&(arr<20)])
#2
arr=np.array([10,15,20,25,30,35])
print(arr[(arr<15)|(arr>30)])
#3
arr=np.array([3,8,15,6,2,20])
arr=np.where(arr>10,0,arr)
print(arr)
#4
arr=np.array([7,14,21,28,35])
arr_new=np.where(arr>20,"high","low")
print(arr_new)
#5
arr=np.arange(0,10)
arr_new=np.where(arr%2==0,arr,arr*10)
print(arr_new)
#6
arr=np.array([[10,25,30],
              [40,5,15],
              [20,35,50]])
print(arr[np.where((arr>20)&(arr<40))])
#7
arr=np.arange(1,7)
print(arr[np.where(arr%3!=0)])
#8
arr=np.random.randint(0,100,10)
arr_new=np.where(arr>50,arr,50)
print(f"랜덤정수배열: {arr}\n50이상은 그대로, 미만은 50화: {arr_new}")
#9
arr=np.array([[5,50,94],
              [20,75,10],
              [60,30,85]])

result = np.where(arr > 70, "A",
         np.where(arr >= 30, "B", "C"))
print(result)

[12 18]
[10 35]
[3 8 0 6 2 0]
['low' 'low' 'high' 'high' 'high']
[ 0 10  2 30  4 50  6 70  8 90]
[25 30 35]
[1 2 4 5]
랜덤정수배열: [55 29 89 35 63 15 84 44 72 24]
50이상은 그대로, 미만은 50화: [55 50 89 50 63 50 84 50 72 50]
[['C' 'B' 'A']
 ['C' 'A' 'C']
 ['B' 'B' 'A']]
